title: EPIC
description: DD4hep Geometry Description of the EPIC Experiment

url: https://wdconinc.github.io
baseurl: /epic

theme: minima

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

exclude:
  - bin/
  - lib/
  - share/
  - install/
  - artifacts/*.prim
  - artifacts/build*/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
