/control/verbose 2
/run/initialize

/gps/verbose 2
/gps/particle pi-
/gps/number 1

/gps/ene/type Gauss
/gps/ene/mono  10.0 GeV
/gps/ene/sigma 3.0 GeV

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0.0 0.0 0.0 cm
/gps/pos/radius 0.01 cm
/gps/pos/halfz  10 cm
/gps/position 0 0 0 cm

#/gps/direction 0 0.1 1.0
/gps/ang/type iso
/gps/ang/mintheta  10 degree
/gps/ang/maxtheta  170 degree

/run/beamOn 100
