#/vis/open OGL 1500x1000-0+0
/vis/open OGL 3500x1800-0+0


/vis/viewer/set/viewpointThetaPhi 260 -40
#/vis/viewer/set/viewpointThetaPhi 200 -20
#/vis/viewer/set/viewpointThetaPhi 90 -90
#/vis/viewer/set/viewpointThetaPhi 186 -60

/vis/viewer/set/background white
/vis/drawVolume
/vis/viewer/zoom 1.8
#/vis/viewer/zoom 2
#/vis/viewer/zoom 2
#/vis/viewer/set/style wireframe
#/vis/scene/add/axes 0 0 0 1 m
/vis/viewer/addCutawayPlane 0 0 0 m 1 0 0
#/vis/viewer/addCutawayPlane 0 0 0 m 0 -1 0
/vis/scene/add/trajectories rich smooth
/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 2

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/invert true
#/vis/filtering/trajectories/particleFilter-0/verbose true
#/vis/filtering/trajectories/particleFilter-0/active true

/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 2 MeV 1000 GeV

/vis/ogl/set/displayListLimit 5000000

/vis/viewer/flush

#/run/beamOn 1

#/control/execute macro/gun.mac

