# Usage example:
#   npsim --runType vis --compactFile athena.xml --random.seed 1 --enableGun --gun.energy 2*GeV --gun.thetaMin 90*deg --gun.thetaMax 90*deg --gun.distribution uniform --macro macro/vis_OGL_along_z_beamOn_1.mac --outputFile test.root
/vis/open OGL 1920x1080
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/viewer/zoom 10
/vis/viewer/flush
/vis/scene/add/trajectories
/vis/scene/add/hits
/run/beamOn 1
