name: Celeritas

on:
  workflow_call:
    inputs:
      detector_configs:
        required: true
        type: string

jobs:
  celeritas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        detector_config: ${{fromJson(inputs.detector_configs)}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: build-gcc-fast-eic-shell
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        network_types: "none"
        setup: install/bin/thisepic.sh
        run: |
          # convert to gdml, but with sensitive detectors included
          scripts/convert_to_gdml.py --compact $DETECTOR_PATH/${{matrix.detector_config}}.xml --output ${{matrix.detector_config}}.gdml | grep -v -A5 -B2 CUTS0100
          # create celeritas input file from template
          cat .github/workflows/celeritas.json | envsubst > ${{matrix.detector_config}}.json
          # run celeritas
          celer-g4 ${{matrix.detector_config}}.json
