name: Convert to GDML

on:
  workflow_call:
    inputs:
      detector_configs:
        required: true
        type: string

jobs:
  convert-to-gdml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: build-gcc-full-eic-shell
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v5
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "eic_xl:nightly"
        network_types: "none"
        setup: install/bin/thisepic.sh
        run: |
          IFS=, read -a configs <<< "${{inputs.detector_configs}}"
          for config in ${configs[@]} ; do
            echo "::group::${config}" ;
            geoConverter -compact2gdml -input ${DETECTOR_PATH}/${config}.xml -output ${config}.gdml ;
            echo "::endgroup::" ;
          done
    - uses: actions/upload-artifact@v4
      with:
        name: gdml
        path: "*.gdml"
        if-no-files-found: error
