on:
  schedule:
    - cron:  '30 11 * * 3' # 11:30 UTC = 07:30 EDT on Wednesday
  workflow_dispatch:

jobs:
  generate-weekly-meeting-slides:
    runs-on: ubuntu-latest
    steps:
    - uses: eic/generate-meeting-slides@v2
      with:
        since: "1 week ago"
        config: |
          repos:  
            - name: ${{ github.repository }}
              do_stale: true
              stale_label: stale
              wip_label: WIP
              do_open_prs: true
              do_merged_prs: true
              do_recent_issues: true
